site_name: NZDGGS documentations
repo_name: am2222/nzdggs
repo_url: https://github.com/am2222/nzdggs
theme: 
  name: readthedocs
  font:
    text: Ubuntu
    code: Ubuntu Mono
  features:
    - instant

copyright: Copyright &copy; 2019 - 2020 TheSpatiallab
